### ISSUE TITLE
Wrong package name

### ISSUE THREAD

**Issue by essofyany** [marucjmar/any-routing#3]
Hi there 

I tried to install the packages mentioned in the ReadMe file and I noticed that there is a typo in the package name @any-routing/annontation-plugin

![Capture d’écran du 2024-01-15 16-54-58](https://github.com/marucjmar/any-routing/assets/62668827/6ac7dd33-57a7-4d6c-a5b8-968c957e896f)

**Comment by marucjmar** [comment]
Thanks for report, fixed by f13eb5a
