### ISSUE TITLE
TypeScript types are missing

### ISSUE THREAD

**Issue by alamenai** [marucjmar/any-routing#4]
Hi @marucjmar ,

I'm encountering this [issue ](https://github.com/mapbox/mapbox-gl-js/issues/13184)and I guess your package will solve it, however it is not compatible with TypeScript.

![image](https://github.com/marucjmar/any-routing/assets/20143684/0df29393-35b4-4912-a9e8-b8092575d17f)

**Comment by marucjmar** [comment]
Thanks for report. Should work with version 0.1.1
